export const REQUIRED_COLUMNS = [
  "companyEmail",
  "firstName",
  "lastName",
  "jobTitle",
  "department",
  "supervisorEmail",
] as const;

export const OPTIONAL_COLUMNS = [
  "middleName",
  "personalEmail",
  "birthday",
  "address",
  "city",
  "province",
  "country",
  "emergencyContactName",
  "emergencyContact",
] as const;

export const TEMPLATE_COLUMNS = [...REQUIRED_COLUMNS, ...OPTIONAL_COLUMNS];

export type BulkOnboardingTemplateRow = Record<(typeof TEMPLATE_COLUMNS)[number], string>;

export const TEMPLATE_SAMPLE_ROWS: BulkOnboardingTemplateRow[] = [
  {
    companyEmail: "maria.santos@company.com",
    firstName: "Maria",
    lastName: "Santos",
    jobTitle: "Nurse",
    department: "Operations",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Reyes",
    personalEmail: "maria.personal@example.com",
    birthday: "1995-06-15",
    address: "123 Sample Street",
    city: "Quezon City",
    province: "Metro Manila",
    country: "Philippines",
    emergencyContactName: "Juan Santos",
    emergencyContact: "09171234567",
  },
  {
    companyEmail: "juan.reyes@company.com",
    firstName: "Juan",
    lastName: "Reyes",
    jobTitle: "Software Engineer",
    department: "Engineering",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Cruz",
    personalEmail: "juan.personal@example.com",
    birthday: "1992-03-22",
    address: "45 Mabini Avenue",
    city: "Makati",
    province: "Metro Manila",
    country: "Philippines",
    emergencyContactName: "Ana Reyes",
    emergencyContact: "09181234567",
  },
  {
    companyEmail: "ana.cruz@company.com",
    firstName: "Ana",
    lastName: "Cruz",
    jobTitle: "HR Coordinator",
    department: "People Operations",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Lopez",
    personalEmail: "ana.personal@example.com",
    birthday: "1998-11-08",
    address: "78 Rizal Street",
    city: "Pasig",
    province: "Metro Manila",
    country: "Philippines",
    emergencyContactName: "Pedro Cruz",
    emergencyContact: "09191234567",
  },
  {
    companyEmail: "pedro.ramos@company.com",
    firstName: "Pedro",
    lastName: "Ramos",
    jobTitle: "Accountant",
    department: "Finance",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Garcia",
    personalEmail: "pedro.personal@example.com",
    birthday: "1990-01-14",
    address: "12 Bonifacio Road",
    city: "Taguig",
    province: "Metro Manila",
    country: "Philippines",
    emergencyContactName: "Rosa Ramos",
    emergencyContact: "09201234567",
  },
  {
    companyEmail: "rosa.garcia@company.com",
    firstName: "Rosa",
    lastName: "Garcia",
    jobTitle: "Customer Support Specialist",
    department: "Customer Success",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Mendoza",
    personalEmail: "rosa.personal@example.com",
    birthday: "1996-07-30",
    address: "56 Del Pilar Street",
    city: "Manila",
    province: "Metro Manila",
    country: "Philippines",
    emergencyContactName: "Miguel Garcia",
    emergencyContact: "09211234567",
  },
  {
    companyEmail: "miguel.torres@company.com",
    firstName: "Miguel",
    lastName: "Torres",
    jobTitle: "Sales Representative",
    department: "Sales",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Santos",
    personalEmail: "miguel.personal@example.com",
    birthday: "1993-09-05",
    address: "90 Aguinaldo Highway",
    city: "Cavite City",
    province: "Cavite",
    country: "Philippines",
    emergencyContactName: "Carla Torres",
    emergencyContact: "09221234567",
  },
  {
    companyEmail: "carla.mendoza@company.com",
    firstName: "Carla",
    lastName: "Mendoza",
    jobTitle: "Marketing Associate",
    department: "Marketing",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Flores",
    personalEmail: "carla.personal@example.com",
    birthday: "1997-12-19",
    address: "34 Luna Street",
    city: "Cebu City",
    province: "Cebu",
    country: "Philippines",
    emergencyContactName: "Diego Mendoza",
    emergencyContact: "09231234567",
  },
  {
    companyEmail: "diego.fernandez@company.com",
    firstName: "Diego",
    lastName: "Fernandez",
    jobTitle: "Data Analyst",
    department: "Analytics",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Aquino",
    personalEmail: "diego.personal@example.com",
    birthday: "1994-04-27",
    address: "21 Burgos Avenue",
    city: "Davao City",
    province: "Davao del Sur",
    country: "Philippines",
    emergencyContactName: "Sofia Fernandez",
    emergencyContact: "09241234567",
  },
  {
    companyEmail: "sofia.aquino@company.com",
    firstName: "Sofia",
    lastName: "Aquino",
    jobTitle: "Operations Associate",
    department: "Operations",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Bautista",
    personalEmail: "sofia.personal@example.com",
    birthday: "1999-02-11",
    address: "67 Quezon Boulevard",
    city: "Iloilo City",
    province: "Iloilo",
    country: "Philippines",
    emergencyContactName: "Luis Aquino",
    emergencyContact: "09251234567",
  },
  {
    companyEmail: "luis.bautista@company.com",
    firstName: "Luis",
    lastName: "Bautista",
    jobTitle: "IT Support Specialist",
    department: "IT",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "Navarro",
    personalEmail: "luis.personal@example.com",
    birthday: "1991-08-03",
    address: "88 P. Burgos Street",
    city: "Baguio",
    province: "Benguet",
    country: "Philippines",
    emergencyContactName: "Maria Bautista",
    emergencyContact: "09261234567",
  },
];

function autosizeTemplateColumns(rows: BulkOnboardingTemplateRow[]) {
  return TEMPLATE_COLUMNS.map((column) => {
    const longestValue = rows.reduce(
      (longest, row) => Math.max(longest, String(row[column] ?? "").length),
      column.length,
    );

    return { wch: Math.min(Math.max(longestValue + 2, 12), 42) };
  });
}

export async function downloadBulkOnboardingTemplate() {
  const XLSX = await import("xlsx");
  const worksheet = XLSX.utils.json_to_sheet(TEMPLATE_SAMPLE_ROWS, {
    header: [...TEMPLATE_COLUMNS],
  });
  worksheet["!cols"] = autosizeTemplateColumns(TEMPLATE_SAMPLE_ROWS);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Bulk onboarding");
  XLSX.writeFile(workbook, "bulk-onboarding-template.xlsx");
}
