export const REQUIRED_COLUMNS = [
  "companyEmail",
  "firstName",
  "lastName",
  "jobTitle",
  "department",
  "supervisorEmail",
] as const;

export const OPTIONAL_COLUMNS = [
  "middleName",
  "personalEmail",
  "birthday",
  "address",
  "city",
  "province",
  "country",
  "emergencyContactName",
  "emergencyContact",
] as const;

export const TEMPLATE_COLUMNS = [...REQUIRED_COLUMNS, ...OPTIONAL_COLUMNS];

export type BulkOnboardingTemplateRow = Record<(typeof TEMPLATE_COLUMNS)[number], string>;

export const TEMPLATE_SAMPLE_ROWS: BulkOnboardingTemplateRow[] = [
  {
    companyEmail: "maria.santos@company.com",
    firstName: "Maria",
    lastName: "Santos",
    jobTitle: "Nurse",
    department: "Operations",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "juan.reyes@company.com",
    firstName: "Juan",
    lastName: "Reyes",
    jobTitle: "Software Engineer",
    department: "Engineering",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "ana.cruz@company.com",
    firstName: "Ana",
    lastName: "Cruz",
    jobTitle: "HR Coordinator",
    department: "People Operations",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "pedro.ramos@company.com",
    firstName: "Pedro",
    lastName: "Ramos",
    jobTitle: "Accountant",
    department: "Finance",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "rosa.garcia@company.com",
    firstName: "Rosa",
    lastName: "Garcia",
    jobTitle: "Customer Support Specialist",
    department: "Customer Success",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "miguel.torres@company.com",
    firstName: "Miguel",
    lastName: "Torres",
    jobTitle: "Sales Representative",
    department: "Sales",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "carla.mendoza@company.com",
    firstName: "Carla",
    lastName: "Mendoza",
    jobTitle: "Marketing Associate",
    department: "Marketing",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "diego.fernandez@company.com",
    firstName: "Diego",
    lastName: "Fernandez",
    jobTitle: "Data Analyst",
    department: "Analytics",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "sofia.aquino@company.com",
    firstName: "Sofia",
    lastName: "Aquino",
    jobTitle: "Operations Associate",
    department: "Operations",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
  {
    companyEmail: "luis.bautista@company.com",
    firstName: "Luis",
    lastName: "Bautista",
    jobTitle: "IT Support Specialist",
    department: "IT",
    supervisorEmail: "allenkurtds.dev@gmail.com",
    middleName: "",
    personalEmail: "",
    birthday: "",
    address: "",
    city: "",
    province: "",
    country: "",
    emergencyContactName: "",
    emergencyContact: "",
  },
];

function autosizeTemplateColumns(rows: BulkOnboardingTemplateRow[]) {
  return TEMPLATE_COLUMNS.map((column) => {
    const longestValue = rows.reduce(
      (longest, row) => Math.max(longest, String(row[column] ?? "").length),
      column.length,
    );

    return { wch: Math.min(Math.max(longestValue + 2, 12), 42) };
  });
}

export async function downloadBulkOnboardingTemplate() {
  const XLSX = await import("xlsx");
  const worksheet = XLSX.utils.json_to_sheet(TEMPLATE_SAMPLE_ROWS, {
    header: [...TEMPLATE_COLUMNS],
  });
  worksheet["!cols"] = autosizeTemplateColumns(TEMPLATE_SAMPLE_ROWS);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Bulk onboarding");
  XLSX.writeFile(workbook, "bulk-onboarding-template.xlsx");
}
