/** Validated body for POST /api/v1/clearance/:requestId/reject. Note is required. */
export interface RejectClearanceRequestDto {
  note: string;
}

/** Validated body for POST /api/v1/clearance/:requestId/sign. Note is optional. */
export interface SignClearanceRequestDto {
  /** PNG data URL generated by the client from draw/type/upload signature input. */
  signatureImage: string;
  note?: string;
}
