/**
 * Stable machine-readable error codes returned by API error responses.
 * Clients can use these codes for branching without parsing human-readable messages.
 */
export const API_ERROR_CODES = {
  EMPLOYEE_NOT_FOUND: "EMPLOYEE_NOT_FOUND",
  INVALID_EMPLOYEE_PROFILE_UPDATE: "INVALID_EMPLOYEE_PROFILE_UPDATE",
  INVALID_EMPLOYEE_STATUS: "INVALID_EMPLOYEE_STATUS",
  INVALID_ENUM_VALUE: "INVALID_ENUM_VALUE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  CANNOT_DEACTIVATE_SELF: "CANNOT_DEACTIVATE_SELF",
  CANNOT_DEACTIVATE_LAST_ADMIN: "CANNOT_DEACTIVATE_LAST_ADMIN",
  CANNOT_CHANGE_OWN_ROLE: "CANNOT_CHANGE_OWN_ROLE",
  CANNOT_DEMOTE_LAST_ADMIN: "CANNOT_DEMOTE_LAST_ADMIN",
  USER_ALREADY_DEACTIVATED: "USER_ALREADY_DEACTIVATED",
  INVALID_USER_ROLE: "INVALID_USER_ROLE",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  EMPLOYEE_ALREADY_EXISTS: "EMPLOYEE_ALREADY_EXISTS",
  SUPERVISOR_NOT_FOUND: "SUPERVISOR_NOT_FOUND",
  ONBOARDING_FAILED: "ONBOARDING_FAILED",
  INVALID_EMERGENCY_CONTACT_PHONE: "INVALID_EMERGENCY_CONTACT_PHONE",
  EMERGENCY_CONTACT_PHONE_ALREADY_IN_USE: "EMERGENCY_CONTACT_PHONE_ALREADY_IN_USE",
  FORBIDDEN: "FORBIDDEN",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  CUSTOM_FIELD_NOT_FOUND: "CUSTOM_FIELD_NOT_FOUND",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_ALREADY_ACCEPTED: "INVITATION_ALREADY_ACCEPTED",
  ACCOUNT_ALREADY_CREATED: "ACCOUNT_ALREADY_CREATED",
  ONBOARDING_RECORD_NOT_FOUND: "ONBOARDING_RECORD_NOT_FOUND",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVITATION_DELIVERY_FAILED: "INVITATION_DELIVERY_FAILED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
