/**
 * Stable machine-readable error codes returned by API error responses.
 * Clients can use these codes for branching without parsing human-readable messages.
 */
export const API_ERROR_CODES = {
  EMPLOYEE_NOT_FOUND: "EMPLOYEE_NOT_FOUND",
  INVALID_EMPLOYEE_STATUS: "INVALID_EMPLOYEE_STATUS",
  INVALID_ENUM_VALUE: "INVALID_ENUM_VALUE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  CANNOT_DEACTIVATE_SELF: "CANNOT_DEACTIVATE_SELF",
  CANNOT_DEACTIVATE_LAST_ADMIN: "CANNOT_DEACTIVATE_LAST_ADMIN",
  USER_ALREADY_DEACTIVATED: "USER_ALREADY_DEACTIVATED",
  INVALID_USER_ROLE: "INVALID_USER_ROLE",
  VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
