/**
 * Stable machine-readable error codes returned by API error responses.
 * Clients can use these codes for branching without parsing human-readable messages.
 */
export const API_ERROR_CODES = {
  EMPLOYEE_NOT_FOUND: "EMPLOYEE_NOT_FOUND",
  INVALID_EMPLOYEE_PROFILE_UPDATE: "INVALID_EMPLOYEE_PROFILE_UPDATE",
  INVALID_EMPLOYEE_STATUS: "INVALID_EMPLOYEE_STATUS",
  INVALID_ENUM_VALUE: "INVALID_ENUM_VALUE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  CANNOT_DEACTIVATE_SELF: "CANNOT_DEACTIVATE_SELF",
  CANNOT_DEACTIVATE_LAST_ADMIN: "CANNOT_DEACTIVATE_LAST_ADMIN",
  CANNOT_CHANGE_OWN_ROLE: "CANNOT_CHANGE_OWN_ROLE",
  CANNOT_DEMOTE_LAST_ADMIN: "CANNOT_DEMOTE_LAST_ADMIN",
  USER_ALREADY_DEACTIVATED: "USER_ALREADY_DEACTIVATED",
  INVALID_USER_ROLE: "INVALID_USER_ROLE",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_SUPERVISOR: "NOT_SUPERVISOR",
  REVIEWER_NOT_EMPLOYEE: "REVIEWER_NOT_EMPLOYEE",
  EVALUATION_NOT_FOUND: "EVALUATION_NOT_FOUND",
  EVALUATION_ALREADY_SENT: "EVALUATION_ALREADY_SENT",
  NOT_EVALUATION_REVIEWER: "NOT_EVALUATION_REVIEWER",
  SURVEY_NOT_FOUND: "SURVEY_NOT_FOUND",
  CREATOR_NOT_EMPLOYEE: "CREATOR_NOT_EMPLOYEE",
  NOT_EVALUATION_REVIEWEE: "NOT_EVALUATION_REVIEWEE",
  EVALUATION_NOT_SENT: "EVALUATION_NOT_SENT",
  EVALUATION_ALREADY_ACKNOWLEDGED: "EVALUATION_ALREADY_ACKNOWLEDGED",
  REVIEWEE_NOT_EMPLOYEE: "REVIEWEE_NOT_EMPLOYEE",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
