ALTER TABLE "pulse_surveys" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "pulse_surveys" ADD COLUMN IF NOT EXISTS "releaseDate" TIMESTAMP(3) NOT NULL DEFAULT NOW();
ALTER TABLE "pulse_surveys" ADD COLUMN IF NOT EXISTS "deadline" TIMESTAMP(3) NOT NULL DEFAULT NOW();

ALTER TABLE "pulse_surveys" ALTER COLUMN "releaseDate" DROP DEFAULT;
ALTER TABLE "pulse_surveys" ALTER COLUMN "deadline" DROP DEFAULT;
